
export type GuardiaoState =
  | 'START'
  | 'DASHBOARD'
  | 'AGENDA_VIEW'
  | 'AGENDA_CONFIRM'
  | 'AGENDA_EDIT'
  | 'VIDEO_SESSION'
  | 'PATIENTS_LIST'
  | 'PATIENT_PROFILE'
  | 'PATIENT_RECORDS'
  | 'PATIENT_PLAN'
  | 'FINANCE_OVERVIEW'
  | 'FINANCE_DETAILS'
  | 'FINANCIAL_DASHBOARD'
  | 'TRIBE_PRO'
  | 'TRIBE_CHAT'
  | 'CHAT_LIST'
  | 'CHAT_ROOM'
  | 'ESCAMBO_MARKET'
  | 'ESCAMBO_PROPOSE'
  | 'ESCAMBO_TRADE'
  | 'ESCAMBO_CONFIRM'
  | 'VAGAS_LIST'
  | 'VAGA_DETAILS'
  | 'VAGA_APPLY'
  | 'SANTUARIO_LIST'
  | 'SANTUARIO_PROFILE'
  | 'SANTUARIO_CONTRACT'
  | 'SETTINGS'
  | 'VIDEO_PREP' // Adding a preparation state
  | 'CUSTOM_INTERVENTION'
  | 'ALQUIMIA_CREATE'
  | 'END';

export const guardiaoTransitions: Record<GuardiaoState, GuardiaoState[]> = {
  START: ['DASHBOARD', 'AGENDA_VIEW', 'PATIENTS_LIST', 'TRIBE_PRO', 'ESCAMBO_MARKET', 'VAGAS_LIST', 'SANTUARIO_LIST', 'FINANCIAL_DASHBOARD', 'SETTINGS', 'CHAT_LIST', 'CUSTOM_INTERVENTION', 'ALQUIMIA_CREATE'],
  DASHBOARD: ['AGENDA_VIEW', 'PATIENTS_LIST', 'FINANCE_OVERVIEW', 'TRIBE_PRO', 'ESCAMBO_MARKET', 'VAGAS_LIST', 'SANTUARIO_LIST', 'FINANCIAL_DASHBOARD', 'SETTINGS', 'CHAT_LIST', 'CUSTOM_INTERVENTION', 'ALQUIMIA_CREATE'],
  AGENDA_VIEW: ['AGENDA_CONFIRM', 'AGENDA_EDIT', 'DASHBOARD', 'VIDEO_SESSION', 'VIDEO_PREP'],
  AGENDA_CONFIRM: ['AGENDA_VIEW', 'AGENDA_EDIT'],
  AGENDA_EDIT: ['AGENDA_VIEW', 'AGENDA_CONFIRM'],
  VIDEO_SESSION: ['DASHBOARD', 'AGENDA_VIEW'],
  PATIENTS_LIST: ['PATIENT_PROFILE', 'DASHBOARD'],
  PATIENT_PROFILE: ['PATIENT_RECORDS', 'DASHBOARD', 'PATIENTS_LIST'],
  PATIENT_RECORDS: ['PATIENT_PROFILE'],
  FINANCE_OVERVIEW: ['FINANCE_DETAILS', 'DASHBOARD'],
  FINANCE_DETAILS: ['FINANCE_OVERVIEW'],
  FINANCIAL_DASHBOARD: ['DASHBOARD'],
  TRIBE_PRO: ['CHAT_LIST', 'TRIBE_CHAT', 'DASHBOARD', 'ALQUIMIA_CREATE', 'ESCAMBO_PROPOSE'],
  TRIBE_CHAT: ['TRIBE_PRO', 'CHAT_LIST'],
  CHAT_LIST: ['CHAT_ROOM', 'DASHBOARD', 'TRIBE_PRO'],
  CHAT_ROOM: ['CHAT_LIST', 'DASHBOARD'],
  ESCAMBO_MARKET: ['ESCAMBO_PROPOSE', 'DASHBOARD', 'ALQUIMIA_CREATE'],
  ALQUIMIA_CREATE: ['ESCAMBO_MARKET', 'DASHBOARD', 'TRIBE_PRO'],
  ESCAMBO_PROPOSE: ['ESCAMBO_CONFIRM', 'ESCAMBO_MARKET', 'TRIBE_PRO'],
  ESCAMBO_CONFIRM: ['DASHBOARD', 'ESCAMBO_MARKET'],
  VAGAS_LIST: ['VAGA_DETAILS', 'DASHBOARD'],
  VAGA_DETAILS: ['VAGA_APPLY', 'VAGAS_LIST'],
  VAGA_APPLY: ['DASHBOARD', 'VAGA_DETAILS'],
  SANTUARIO_LIST: ['SANTUARIO_PROFILE', 'DASHBOARD'],
  SANTUARIO_PROFILE: ['SANTUARIO_CONTRACT', 'SANTUARIO_LIST'],
  SANTUARIO_CONTRACT: ['DASHBOARD', 'SANTUARIO_PROFILE'],
  SETTINGS: ['DASHBOARD'],
  PATIENT_PLAN: ['PATIENTS_LIST', 'DASHBOARD'],
  ESCAMBO_TRADE: ['ESCAMBO_MARKET', 'DASHBOARD'],
  VIDEO_PREP: ['VIDEO_SESSION', 'AGENDA_VIEW', 'DASHBOARD'],
  CUSTOM_INTERVENTION: ['DASHBOARD'],
  END: ['START']
};
