export type FlowProfile = 'BUSCADOR' | 'GUARDIAO' | 'SANTUARIO';

export type FlowDefinition = {
  id: string;
  profile: FlowProfile;
  title: string;
  screens: string[];
  prerequisites: string[];
  expectedFinal: string;
  fallbackScreen: string;
  requiredButtons: Array<'Voltar' | 'Fechar' | 'Cancelar' | 'Confirmar'>;
  endpoints: string[];
  // Some flows are purely client-side (local storage, UI state) and do not
  // touch backend endpoints. We keep them in the registry to preserve the
  // "start/middle/end" contract without lying about API coverage.
  clientOnly?: boolean;
  // Explicitly documented narrative hops where the registry intentionally
  // compresses a multi-step engine path into a product-level journey step.
  allowedNarrativeJumps?: Array<{ from: string; to: string }>;
};

const baseButtons: Array<'Voltar' | 'Fechar' | 'Cancelar' | 'Confirmar'> = [
  'Voltar',
  'Fechar',
  'Cancelar',
  'Confirmar',
];

export const flowRegistry: FlowDefinition[] = [
  {
    id: 'buscador_ritual_diario',
    profile: 'BUSCADOR',
    title: 'Ritual diário com check-in e retorno ao histórico',
    screens: ['DASHBOARD', 'METAMORPHOSIS_CHECKIN', 'METAMORPHOSIS_CAMERA', 'METAMORPHOSIS_MESSAGE', 'METAMORPHOSIS_FEEDBACK', 'HISTORY'],
    prerequisites: ['authenticated', 'role=CLIENT'],
    expectedFinal: 'HISTORY',
    fallbackScreen: 'DASHBOARD',
    requiredButtons: baseButtons,
    endpoints: ['/api/metamorphosis/checkin'],
  },
  {
    id: 'buscador_metamorfose_karma_timelapse',
    profile: 'BUSCADOR',
    title: 'Metamorfose + karma + time-lapse',
    screens: ['DASHBOARD', 'EVOLUTION', 'EVOLUTION_TIMELAPSE', 'TIME_LAPSE_EXPERIENCE'],
    prerequisites: ['authenticated', 'role=CLIENT'],
    expectedFinal: 'TIME_LAPSE_EXPERIENCE',
    fallbackScreen: 'DASHBOARD',
    requiredButtons: baseButtons,
    endpoints: ['/api/metamorphosis/evolution', '/api/oracle/history'],
  },
  {
    id: 'buscador_busca_agenda_confirmacao',
    profile: 'BUSCADOR',
    title: 'Busca + agendamento + confirmação + notificação + acesso à sessão em vídeo',
    screens: ['BOOKING_SEARCH', 'BOOKING_SELECT', 'BOOKING_CONFIRM', 'CHECKOUT', 'PAYMENT_SUCCESS', 'VIDEO_SESSION'],
    prerequisites: ['authenticated', 'role=CLIENT'],
    expectedFinal: 'VIDEO_SESSION',
    fallbackScreen: 'DASHBOARD',
    requiredButtons: baseButtons,
    endpoints: ['/api/appointments/*', '/api/checkout/pay', '/api/notifications/*'],
  },
  {
    id: 'buscador_marketplace_checkout',
    profile: 'BUSCADOR',
    title: 'Marketplace + carrinho + checkout + recibo',
    screens: ['MARKETPLACE', 'CHECKOUT', 'PAYMENT_SUCCESS', 'PAYMENT_HISTORY'],
    prerequisites: ['authenticated', 'role=CLIENT'],
    expectedFinal: 'PAYMENT_HISTORY',
    fallbackScreen: 'DASHBOARD',
    requiredButtons: baseButtons,
    endpoints: ['/api/marketplace/products', '/api/checkout/pay'],
  },
  {
    id: 'buscador_tribo_convite',
    profile: 'BUSCADOR',
    title: 'Tribo convite e interação',
    screens: ['TRIBE_DASH', 'TRIBE_INVITE', 'TRIBE_DASH', 'TRIBE_INTERACTION', 'CHAT_ROOM'],
    prerequisites: ['authenticated', 'role=CLIENT'],
    expectedFinal: 'CHAT_ROOM',
    fallbackScreen: 'DASHBOARD',
    requiredButtons: baseButtons,
    endpoints: ['/api/tribe/*', '/api/chat/*'],
  },
  {
    id: 'buscador_retiro_offline',
    profile: 'BUSCADOR',
    title: 'Tribo: Retiro Offline (silenciar in-app) com retorno seguro',
    screens: ['TRIBE_DASH', 'OFFLINE_RETREAT', 'TRIBE_DASH'],
    prerequisites: ['authenticated', 'role=CLIENT'],
    expectedFinal: 'TRIBE_DASH',
    fallbackScreen: 'DASHBOARD',
    requiredButtons: baseButtons,
    endpoints: ['/api/tribe/sync', '/api/notifications/*'],
  },
  {
    id: 'buscador_pacto_de_alma',
    profile: 'BUSCADOR',
    title: 'Tribo: Pacto de Alma + convite para ampliar a tribo',
    screens: ['TRIBE_DASH', 'SOUL_PACT', 'TRIBE_DASH'],
    prerequisites: ['authenticated', 'role=CLIENT'],
    expectedFinal: 'TRIBE_DASH',
    fallbackScreen: 'TRIBE_DASH',
    requiredButtons: baseButtons,
    endpoints: ['/api/invites/create', '/api/tribe/*'],
  },
  {
    id: 'buscador_circulo_de_cura_checkout',
    profile: 'BUSCADOR',
    title: 'Tribo: Participar do Círculo de Cura (evento + checkout)',
    screens: ['TRIBE_DASH', 'HEALING_CIRCLE', 'CHECKOUT', 'PAYMENT_SUCCESS'],
    prerequisites: ['authenticated', 'role=CLIENT'],
    expectedFinal: 'PAYMENT_SUCCESS',
    fallbackScreen: 'TRIBE_DASH',
    requiredButtons: baseButtons,
    endpoints: ['/api/calendar', '/api/checkout/pay'],
  },
  {
    id: 'buscador_missoes_diarias',
    profile: 'BUSCADOR',
    title: 'Jornada: Missões do dia (client-only) com saída para Karma',
    screens: ['DASHBOARD', 'CLIENT_QUESTS', 'KARMA_WALLET'],
    prerequisites: ['authenticated', 'role=CLIENT'],
    expectedFinal: 'KARMA_WALLET',
    fallbackScreen: 'DASHBOARD',
    requiredButtons: baseButtons,
    endpoints: [],
    clientOnly: true,
  },
  {
    id: 'buscador_grimorio_colecao',
    profile: 'BUSCADOR',
    title: 'Jornada: Grimório da Alma (client-only) com retorno ao core',
    screens: ['GARDEN_VIEW', 'EVO_GRIMOIRE', 'DASHBOARD'],
    prerequisites: ['authenticated', 'role=CLIENT'],
    expectedFinal: 'DASHBOARD',
    fallbackScreen: 'GARDEN_VIEW',
    requiredButtons: baseButtons,
    endpoints: [],
    clientOnly: true,
  },
  {
    id: 'buscador_oraculo_completo',
    profile: 'BUSCADOR',
    title: 'Oráculo completo: portal, embaralhar, revelação e histórico',
    screens: ['DASHBOARD', 'ORACLE_PORTAL', 'ORACLE_SHUFFLE', 'ORACLE_REVEAL', 'ORACLE_HISTORY'],
    prerequisites: ['authenticated', 'role=CLIENT'],
    expectedFinal: 'ORACLE_HISTORY',
    fallbackScreen: 'DASHBOARD',
    requiredButtons: baseButtons,
    endpoints: ['/api/oracle/*'],
  },
  {
    id: 'buscador_jornada_analitica_e_journal',
    profile: 'BUSCADOR',
    title: 'Jornada analítica, histórico expandido e diário do buscador',
    screens: ['DASHBOARD', 'HISTORY', 'EVOLUTION', 'EVOLUTION_ANALYTICS', 'EVOLUTION_ACHIEVEMENTS', 'EVOLUTION_HISTORY', 'CLIENT_JOURNAL'],
    prerequisites: ['authenticated', 'role=CLIENT'],
    expectedFinal: 'CLIENT_JOURNAL',
    fallbackScreen: 'DASHBOARD',
    requiredButtons: baseButtons,
    endpoints: ['/api/metamorphosis/*', '/api/oracle/history'],
  },
  {
    id: 'buscador_chat_social',
    profile: 'BUSCADOR',
    title: 'Tribo e chat social: lista, novo chat, sala e ajustes',
    screens: ['DASHBOARD', 'TRIBE_DASH', 'CHAT_LIST', 'CHAT_NEW', 'CHAT_ROOM', 'CHAT_SETTINGS'],
    prerequisites: ['authenticated', 'role=CLIENT'],
    expectedFinal: 'CHAT_SETTINGS',
    fallbackScreen: 'TRIBE_DASH',
    requiredButtons: baseButtons,
    endpoints: ['/api/chat/*', '/api/tribe/*'],
  },
  {
    id: 'buscador_metamorfose_ritual_retorno',
    profile: 'BUSCADOR',
    title: 'Ritual de metamorfose com retorno ao dashboard',
    screens: ['DASHBOARD', 'METAMORPHOSIS_CHECKIN', 'METAMORPHOSIS_RITUAL', 'DASHBOARD'],
    prerequisites: ['authenticated', 'role=CLIENT'],
    expectedFinal: 'DASHBOARD',
    fallbackScreen: 'DASHBOARD',
    requiredButtons: baseButtons,
    endpoints: ['/api/metamorphosis/*'],
  },
  {
    id: 'buscador_shell_e_config',
    profile: 'BUSCADOR',
    title: 'Shell do buscador: entrada, configurações e encerramento com persistência de perfil',
    screens: ['START', 'DASHBOARD', 'SETTINGS', 'END'],
    prerequisites: ['authenticated', 'role=CLIENT'],
    expectedFinal: 'END',
    fallbackScreen: 'DASHBOARD',
    requiredButtons: baseButtons,
    endpoints: ['/api/users/:id', '/api/auth/roles', '/api/auth/select-role', '/api/finance/*'],
  },
  {
    id: 'guardiao_escambo',
    profile: 'GUARDIAO',
    title: 'Escambo guardião↔guardião',
    screens: ['ESCAMBO_MARKET', 'ESCAMBO_PROPOSE', 'ESCAMBO_CONFIRM'],
    prerequisites: ['authenticated', 'role=PROFESSIONAL'],
    expectedFinal: 'ESCAMBO_CONFIRM',
    fallbackScreen: 'DASHBOARD',
    requiredButtons: baseButtons,
    endpoints: ['/api/alchemy/offers/*', '/api/chat/*'],
  },
  {
    id: 'guardiao_prontuario_consentido',
    profile: 'GUARDIAO',
    title: 'Acesso a prontuário consentido',
    screens: ['PATIENTS_LIST', 'PATIENT_PROFILE', 'PATIENT_RECORDS'],
    prerequisites: ['authenticated', 'role=PROFESSIONAL', 'consent=ACTIVE'],
    expectedFinal: 'PATIENT_RECORDS',
    fallbackScreen: 'PATIENTS_LIST',
    requiredButtons: baseButtons,
    endpoints: ['/api/records/*'],
  },
  {
    id: 'guardiao_intervencao_clinica',
    profile: 'GUARDIAO',
    title: 'Guardião: criar intervenção clínica personalizada',
    screens: ['DASHBOARD', 'CUSTOM_INTERVENTION', 'DASHBOARD'],
    prerequisites: ['authenticated', 'role=PROFESSIONAL'],
    expectedFinal: 'DASHBOARD',
    fallbackScreen: 'DASHBOARD',
    requiredButtons: baseButtons,
    endpoints: ['/api/clinical/interventions'],
  },
  {
    id: 'guardiao_alquimia_criar_oferta',
    profile: 'GUARDIAO',
    title: 'Guardião: criar oferta (Alquimia) com retorno ao marketplace',
    screens: ['DASHBOARD', 'ALQUIMIA_CREATE', 'ESCAMBO_MARKET'],
    prerequisites: ['authenticated', 'role=PROFESSIONAL'],
    expectedFinal: 'ESCAMBO_MARKET',
    fallbackScreen: 'DASHBOARD',
    requiredButtons: baseButtons,
    endpoints: ['/api/marketplace/products'],
  },
  {
    id: 'guardiao_agenda_video',
    profile: 'GUARDIAO',
    title: 'Agenda guardião: preparar, confirmar, editar e conduzir sessão',
    screens: ['START', 'DASHBOARD', 'AGENDA_VIEW', 'AGENDA_CONFIRM', 'AGENDA_EDIT', 'VIDEO_PREP', 'VIDEO_SESSION'],
    prerequisites: ['authenticated', 'role=PROFESSIONAL'],
    expectedFinal: 'VIDEO_SESSION',
    fallbackScreen: 'DASHBOARD',
    requiredButtons: baseButtons,
    endpoints: ['/api/appointments/*'],
  },
  {
    id: 'guardiao_financeiro_expandido',
    profile: 'GUARDIAO',
    title: 'Guardião: visão financeira com drilldown e dashboard financeiro',
    screens: ['DASHBOARD', 'FINANCE_OVERVIEW', 'FINANCE_DETAILS', 'FINANCIAL_DASHBOARD'],
    prerequisites: ['authenticated', 'role=PROFESSIONAL'],
    expectedFinal: 'FINANCIAL_DASHBOARD',
    fallbackScreen: 'DASHBOARD',
    requiredButtons: baseButtons,
    endpoints: ['/api/finance/*'],
  },
  {
    id: 'guardiao_tribo_chat',
    profile: 'GUARDIAO',
    title: 'Guardião: tribo e chat com retorno seguro',
    screens: ['DASHBOARD', 'TRIBE_PRO', 'TRIBE_CHAT', 'CHAT_LIST', 'CHAT_ROOM'],
    prerequisites: ['authenticated', 'role=PROFESSIONAL'],
    expectedFinal: 'CHAT_ROOM',
    fallbackScreen: 'TRIBE_PRO',
    requiredButtons: baseButtons,
    endpoints: ['/api/chat/*', '/api/tribe/*'],
  },
  {
    id: 'guardiao_vagas_completas',
    profile: 'GUARDIAO',
    title: 'Guardião: vagas, detalhes e candidatura',
    screens: ['DASHBOARD', 'VAGAS_LIST', 'VAGA_DETAILS', 'VAGA_APPLY'],
    prerequisites: ['authenticated', 'role=PROFESSIONAL'],
    expectedFinal: 'VAGA_APPLY',
    fallbackScreen: 'DASHBOARD',
    requiredButtons: baseButtons,
    endpoints: ['/api/recruitment/*'],
  },
  {
    id: 'guardiao_santuarios_parceria',
    profile: 'GUARDIAO',
    title: 'Guardião: descobrir santuários e formalizar vínculo',
    screens: ['DASHBOARD', 'SANTUARIO_LIST', 'SANTUARIO_PROFILE', 'SANTUARIO_CONTRACT'],
    prerequisites: ['authenticated', 'role=PROFESSIONAL'],
    expectedFinal: 'SANTUARIO_CONTRACT',
    fallbackScreen: 'DASHBOARD',
    requiredButtons: baseButtons,
    endpoints: ['/api/spaces/*'],
  },
  {
    id: 'guardiao_paciente_plano_e_trade',
    profile: 'GUARDIAO',
    title: 'Guardião: plano terapêutico e estado de troca de escambo',
    screens: ['PATIENTS_LIST', 'PATIENT_PLAN', 'ESCAMBO_MARKET', 'ESCAMBO_TRADE', 'ESCAMBO_CONFIRM'],
    prerequisites: ['authenticated', 'role=PROFESSIONAL'],
    expectedFinal: 'ESCAMBO_CONFIRM',
    fallbackScreen: 'DASHBOARD',
    requiredButtons: baseButtons,
    endpoints: ['/api/alchemy/*', '/api/records/*'],
    allowedNarrativeJumps: [
      { from: 'PATIENTS_LIST', to: 'PATIENT_PLAN' },
      { from: 'ESCAMBO_MARKET', to: 'ESCAMBO_TRADE' },
    ],
  },
  {
    id: 'guardiao_shell_e_config',
    profile: 'GUARDIAO',
    title: 'Shell do guardião: entrada, dashboard e configurações com persistência de perfil',
    screens: ['START', 'DASHBOARD', 'SETTINGS', 'END'],
    prerequisites: ['authenticated', 'role=PROFESSIONAL'],
    expectedFinal: 'END',
    fallbackScreen: 'DASHBOARD',
    requiredButtons: baseButtons,
    endpoints: ['/api/users/:id', '/api/auth/roles', '/api/auth/select-role', '/api/finance/*'],
  },
  {
    id: 'santuario_vagas_entrevista',
    profile: 'SANTUARIO',
    title: 'Vaga santuário -> candidatos/entrevista',
    screens: ['EXEC_DASHBOARD', 'VAGAS_LIST', 'VAGA_CANDIDATES'],
    prerequisites: ['authenticated', 'role=SPACE'],
    expectedFinal: 'VAGA_CANDIDATES',
    fallbackScreen: 'EXEC_DASHBOARD',
    requiredButtons: baseButtons,
    endpoints: ['/api/recruitment/*'],
  },
  {
    id: 'santuario_operacao_completa',
    profile: 'SANTUARIO',
    title: 'Operação do hub: equipe, salas, agenda, financeiro',
    screens: ['EXEC_DASHBOARD', 'PROS_LIST', 'EXEC_DASHBOARD', 'ROOMS_STATUS', 'EXEC_DASHBOARD', 'AGENDA_OVERVIEW', 'EXEC_DASHBOARD', 'FINANCE_OVERVIEW'],
    prerequisites: ['authenticated', 'role=SPACE'],
    expectedFinal: 'FINANCE_OVERVIEW',
    fallbackScreen: 'EXEC_DASHBOARD',
    requiredButtons: baseButtons,
    endpoints: ['/api/spaces/*', '/api/rooms/*', '/api/finance/*'],
  },
  {
    id: 'santuario_inteligencia_preditiva',
    profile: 'SANTUARIO',
    title: 'Santuário: Ocupação preditiva (client-only) com saída para agenda',
    screens: ['EXEC_DASHBOARD', 'PREDICTIVE_OCCUPANCY', 'ROOM_AGENDA'],
    prerequisites: ['authenticated', 'role=SPACE'],
    expectedFinal: 'ROOM_AGENDA',
    fallbackScreen: 'EXEC_DASHBOARD',
    requiredButtons: baseButtons,
    endpoints: [],
    clientOnly: true,
  },
  {
    id: 'santuario_auditoria_interna',
    profile: 'SANTUARIO',
    title: 'Santuário: trilha de auditoria (client-only) com retorno à governança',
    screens: ['EXEC_DASHBOARD', 'RADIANCE_DRILLDOWN', 'AUDIT_LOG', 'GOVERNANCE'],
    prerequisites: ['authenticated', 'role=SPACE'],
    expectedFinal: 'GOVERNANCE',
    fallbackScreen: 'EXEC_DASHBOARD',
    requiredButtons: baseButtons,
    endpoints: [],
    clientOnly: true,
  },
  {
    id: 'santuario_pacientes_operacao',
    profile: 'SANTUARIO',
    title: 'Santuário: atendimento interno de pacientes e agenda local',
    screens: ['START', 'EXEC_DASHBOARD', 'PATIENTS_LIST', 'PATIENT_PROFILE', 'PATIENT_RECORDS', 'AGENDA_EDIT'],
    prerequisites: ['authenticated', 'role=SPACE'],
    expectedFinal: 'AGENDA_EDIT',
    fallbackScreen: 'EXEC_DASHBOARD',
    requiredButtons: baseButtons,
    endpoints: ['/api/records/*', '/api/appointments/*'],
  },
  {
    id: 'santuario_time_e_avaliacao_servico',
    profile: 'SANTUARIO',
    title: 'Santuário: equipe, convite/summon, performance e avaliação de serviço',
    screens: ['EXEC_DASHBOARD', 'PROS_LIST', 'PRO_PROFILE', 'PRO_PERFORMANCE', 'TEAM_SUMMON', 'TEAM_INVITE', 'SERVICE_EVALUATION'],
    prerequisites: ['authenticated', 'role=SPACE'],
    expectedFinal: 'SERVICE_EVALUATION',
    fallbackScreen: 'EXEC_DASHBOARD',
    requiredButtons: baseButtons,
    endpoints: ['/api/spaces/*', '/api/reviews/*'],
  },
  {
    id: 'santuario_salaseestrutura_expandida',
    profile: 'SANTUARIO',
    title: 'Santuário: gestão de salas com criação, detalhe e edição',
    screens: ['EXEC_DASHBOARD', 'ROOMS_STATUS', 'ROOM_CREATE', 'ROOM_DETAILS', 'ROOM_EDIT', 'ROOM_AGENDA'],
    prerequisites: ['authenticated', 'role=SPACE'],
    expectedFinal: 'ROOM_AGENDA',
    fallbackScreen: 'EXEC_DASHBOARD',
    requiredButtons: baseButtons,
    endpoints: ['/api/rooms/*'],
  },
  {
    id: 'santuario_financeiro_expandido',
    profile: 'SANTUARIO',
    title: 'Santuário: financeiro com repasses e projeções',
    screens: ['EXEC_DASHBOARD', 'FINANCE_OVERVIEW', 'FINANCE_REPASSES', 'FINANCE_FORECAST'],
    prerequisites: ['authenticated', 'role=SPACE'],
    expectedFinal: 'FINANCE_FORECAST',
    fallbackScreen: 'EXEC_DASHBOARD',
    requiredButtons: baseButtons,
    endpoints: ['/api/finance/*'],
  },
  {
    id: 'santuario_marketplace_eventos_retiros',
    profile: 'SANTUARIO',
    title: 'Santuário: gestão de marketplace, eventos e retiros',
    screens: ['EXEC_DASHBOARD', 'MARKETPLACE_MANAGE', 'MARKETPLACE_CREATE', 'EVENTS_MANAGE', 'EVENT_CREATE', 'RETREATS_MANAGE'],
    prerequisites: ['authenticated', 'role=SPACE'],
    expectedFinal: 'RETREATS_MANAGE',
    fallbackScreen: 'EXEC_DASHBOARD',
    requiredButtons: baseButtons,
    endpoints: ['/api/marketplace/*', '/api/events/*'],
    allowedNarrativeJumps: [
      { from: 'EVENT_CREATE', to: 'RETREATS_MANAGE' },
    ],
  },
  {
    id: 'santuario_recrutamento_completo',
    profile: 'SANTUARIO',
    title: 'Santuário: criação de vaga e análise de candidatos',
    screens: ['EXEC_DASHBOARD', 'VAGAS_LIST', 'VAGA_CREATE', 'VAGA_CANDIDATES'],
    prerequisites: ['authenticated', 'role=SPACE'],
    expectedFinal: 'VAGA_CANDIDATES',
    fallbackScreen: 'EXEC_DASHBOARD',
    requiredButtons: baseButtons,
    endpoints: ['/api/recruitment/*'],
  },
  {
    id: 'santuario_analytics_reputacao_chat',
    profile: 'SANTUARIO',
    title: 'Santuário: reputação, analytics e comunicação interna',
    screens: ['EXEC_DASHBOARD', 'REPUTATION_OVERVIEW', 'ANALYTICS_DASH', 'CHAT_LIST', 'CHAT_ROOM'],
    prerequisites: ['authenticated', 'role=SPACE'],
    expectedFinal: 'CHAT_ROOM',
    fallbackScreen: 'EXEC_DASHBOARD',
    requiredButtons: baseButtons,
    endpoints: ['/api/chat/*', '/api/analytics/*'],
  },
  {
    id: 'santuario_shell_e_encerramento',
    profile: 'SANTUARIO',
    title: 'Shell do santuário: entrada e encerramento de fluxo',
    screens: ['START', 'EXEC_DASHBOARD', 'END'],
    prerequisites: ['authenticated', 'role=SPACE'],
    expectedFinal: 'END',
    fallbackScreen: 'EXEC_DASHBOARD',
    requiredButtons: baseButtons,
    endpoints: [],
    clientOnly: true,
  },
  {
    id: 'santuario_avaliacao_servico',
    profile: 'SANTUARIO',
    title: 'Santuário: avaliação de serviço (client-only) com retorno ao dashboard',
    screens: ['PRO_PROFILE', 'SERVICE_EVALUATION', 'EXEC_DASHBOARD'],
    prerequisites: ['authenticated', 'role=SPACE'],
    expectedFinal: 'EXEC_DASHBOARD',
    fallbackScreen: 'EXEC_DASHBOARD',
    requiredButtons: baseButtons,
    endpoints: [],
    clientOnly: true,
  },
];

export const flowRegistryByProfile: Record<FlowProfile, FlowDefinition[]> = {
  BUSCADOR: flowRegistry.filter((flow) => flow.profile === 'BUSCADOR'),
  GUARDIAO: flowRegistry.filter((flow) => flow.profile === 'GUARDIAO'),
  SANTUARIO: flowRegistry.filter((flow) => flow.profile === 'SANTUARIO'),
};
