
export type SantuarioState =
  | 'START'
  | 'EXEC_DASHBOARD'
  | 'PROS_LIST'
  | 'PRO_PROFILE'
  | 'PRO_PERFORMANCE'
  | 'PATIENTS_LIST'
  | 'PATIENT_PROFILE'
  | 'PATIENT_RECORDS'
  | 'AGENDA_OVERVIEW'
  | 'AGENDA_EDIT'
  | 'ROOMS_STATUS'
  | 'ROOM_DETAILS'
  | 'FINANCE_OVERVIEW'
  | 'FINANCE_REPASSES'
  | 'FINANCE_FORECAST'
  | 'MARKETPLACE_MANAGE'
  | 'MARKETPLACE_CREATE'
  | 'EVENTS_MANAGE'
  | 'EVENT_CREATE'
  | 'VAGAS_LIST'
  | 'VAGA_CREATE'
  | 'VAGA_CANDIDATES'
  | 'REPUTATION_OVERVIEW'
  | 'ANALYTICS_DASH'
  | 'GOVERNANCE'
  | 'END';

export const santuarioTransitions: Record<SantuarioState, SantuarioState[]> = {
  START: ['EXEC_DASHBOARD', 'PROS_LIST','PATIENTS_LIST','AGENDA_OVERVIEW','ROOMS_STATUS','FINANCE_OVERVIEW','MARKETPLACE_MANAGE','EVENTS_MANAGE','VAGAS_LIST','REPUTATION_OVERVIEW','ANALYTICS_DASH','GOVERNANCE'],
  EXEC_DASHBOARD: ['PROS_LIST','PATIENTS_LIST','AGENDA_OVERVIEW','ROOMS_STATUS','FINANCE_OVERVIEW','MARKETPLACE_MANAGE','EVENTS_MANAGE','VAGAS_LIST','REPUTATION_OVERVIEW','ANALYTICS_DASH','GOVERNANCE'],
  PROS_LIST: ['PRO_PROFILE','PRO_PERFORMANCE','EXEC_DASHBOARD'],
  PRO_PROFILE: ['PRO_PERFORMANCE', 'PROS_LIST'],
  PRO_PERFORMANCE: ['PRO_PROFILE', 'PROS_LIST'],
  PATIENTS_LIST: ['PATIENT_PROFILE','EXEC_DASHBOARD'],
  PATIENT_PROFILE: ['PATIENT_RECORDS', 'PATIENTS_LIST'],
  PATIENT_RECORDS: ['PATIENT_PROFILE'],
  AGENDA_OVERVIEW: ['AGENDA_EDIT','EXEC_DASHBOARD'],
  AGENDA_EDIT: ['AGENDA_OVERVIEW'],
  ROOMS_STATUS: ['ROOM_DETAILS','EXEC_DASHBOARD'],
  ROOM_DETAILS: ['ROOMS_STATUS'],
  FINANCE_OVERVIEW: ['FINANCE_REPASSES','FINANCE_FORECAST','EXEC_DASHBOARD'],
  FINANCE_REPASSES: ['FINANCE_OVERVIEW'],
  FINANCE_FORECAST: ['FINANCE_OVERVIEW'],
  MARKETPLACE_MANAGE: ['MARKETPLACE_CREATE','EXEC_DASHBOARD'],
  MARKETPLACE_CREATE: ['MARKETPLACE_MANAGE'],
  EVENTS_MANAGE: ['EVENT_CREATE','EXEC_DASHBOARD'],
  EVENT_CREATE: ['EVENTS_MANAGE'],
  VAGAS_LIST: ['VAGA_CREATE','VAGA_CANDIDATES','EXEC_DASHBOARD'],
  VAGA_CREATE: ['VAGAS_LIST'],
  VAGA_CANDIDATES: ['VAGAS_LIST'],
  REPUTATION_OVERVIEW: ['EXEC_DASHBOARD'],
  ANALYTICS_DASH: ['EXEC_DASHBOARD'],
  GOVERNANCE: ['EXEC_DASHBOARD'],
  END: ['START']
};
