
export type SantuarioState =
  | 'START'
  | 'EXEC_DASHBOARD'
  | 'PROS_LIST'
  | 'PRO_PROFILE'
  | 'PRO_PERFORMANCE'
  | 'TEAM_SUMMON'
  | 'TEAM_INVITE'
  | 'PATIENTS_LIST'
  | 'PATIENT_PROFILE'
  | 'PATIENT_RECORDS'
  | 'AGENDA_OVERVIEW'
  | 'AGENDA_EDIT'
  | 'ROOMS_STATUS'
  | 'ROOM_DETAILS'
  | 'ROOM_EDIT'
  | 'ROOM_CREATE'
  | 'ROOM_AGENDA'
  | 'FINANCE_OVERVIEW'
  | 'FINANCE_REPASSES'
  | 'FINANCE_FORECAST'
  | 'MARKETPLACE_MANAGE'
  | 'MARKETPLACE_CREATE'
  | 'EVENTS_MANAGE'
  | 'EVENT_CREATE'
  | 'RETREATS_MANAGE'
  | 'SERVICE_EVALUATION'
  | 'VAGAS_LIST'
  | 'VAGA_CREATE'
  | 'VAGA_CANDIDATES'
  | 'REPUTATION_OVERVIEW'
  | 'ANALYTICS_DASH'
  | 'GOVERNANCE'
  | 'CHAT_LIST'
  | 'CHAT_ROOM'
  | 'PREDICTIVE_OCCUPANCY'
  | 'AUDIT_LOG'
  | 'RADIANCE_DRILLDOWN'
  | 'END';

export const santuarioTransitions: Record<SantuarioState, SantuarioState[]> = {
  START: ['EXEC_DASHBOARD', 'PROS_LIST','PATIENTS_LIST','AGENDA_OVERVIEW','ROOMS_STATUS','FINANCE_OVERVIEW','MARKETPLACE_MANAGE','EVENTS_MANAGE','VAGAS_LIST','REPUTATION_OVERVIEW','ANALYTICS_DASH','GOVERNANCE', 'CHAT_LIST', 'PREDICTIVE_OCCUPANCY', 'AUDIT_LOG'],
  EXEC_DASHBOARD: ['PROS_LIST','PATIENTS_LIST','AGENDA_OVERVIEW','ROOMS_STATUS','FINANCE_OVERVIEW','MARKETPLACE_MANAGE','EVENTS_MANAGE','VAGAS_LIST','REPUTATION_OVERVIEW','ANALYTICS_DASH','GOVERNANCE', 'CHAT_LIST', 'TEAM_SUMMON', 'TEAM_INVITE', 'ROOM_CREATE', 'PREDICTIVE_OCCUPANCY', 'AUDIT_LOG', 'RADIANCE_DRILLDOWN'],
  PROS_LIST: ['PRO_PROFILE','PRO_PERFORMANCE','EXEC_DASHBOARD', 'TEAM_SUMMON', 'TEAM_INVITE'],
  PRO_PROFILE: ['PRO_PERFORMANCE', 'PROS_LIST'],
  PRO_PERFORMANCE: ['PRO_PROFILE', 'PROS_LIST'],
  PATIENTS_LIST: ['PATIENT_PROFILE','EXEC_DASHBOARD'],
  PATIENT_PROFILE: ['PATIENT_RECORDS', 'PATIENTS_LIST'],
  PATIENT_RECORDS: ['PATIENT_PROFILE'],
  AGENDA_OVERVIEW: ['AGENDA_EDIT','EXEC_DASHBOARD'],
  AGENDA_EDIT: ['AGENDA_OVERVIEW'],
  ROOMS_STATUS: ['ROOM_DETAILS','EXEC_DASHBOARD', 'ROOM_CREATE'],
  ROOM_CREATE: ['ROOMS_STATUS', 'EXEC_DASHBOARD'],
  ROOM_DETAILS: ['ROOMS_STATUS'],
  FINANCE_OVERVIEW: ['FINANCE_REPASSES','FINANCE_FORECAST','EXEC_DASHBOARD'],
  FINANCE_REPASSES: ['FINANCE_OVERVIEW'],
  FINANCE_FORECAST: ['FINANCE_OVERVIEW'],
  MARKETPLACE_MANAGE: ['MARKETPLACE_CREATE','EXEC_DASHBOARD'],
  MARKETPLACE_CREATE: ['MARKETPLACE_MANAGE'],
  EVENTS_MANAGE: ['EVENT_CREATE','EXEC_DASHBOARD'],
  EVENT_CREATE: ['EVENTS_MANAGE'],
  RETREATS_MANAGE: ['EXEC_DASHBOARD'],
  VAGAS_LIST: ['VAGA_CREATE','VAGA_CANDIDATES','EXEC_DASHBOARD'],
  VAGA_CREATE: ['VAGAS_LIST'],
  VAGA_CANDIDATES: ['VAGAS_LIST'],
  REPUTATION_OVERVIEW: ['EXEC_DASHBOARD'],
  ANALYTICS_DASH: ['EXEC_DASHBOARD'],
  GOVERNANCE: ['EXEC_DASHBOARD'],
  CHAT_LIST: ['CHAT_ROOM', 'EXEC_DASHBOARD'],
  CHAT_ROOM: ['CHAT_LIST'],
  TEAM_SUMMON: ['PROS_LIST', 'EXEC_DASHBOARD'],
  TEAM_INVITE: ['PROS_LIST', 'EXEC_DASHBOARD'],
  ROOM_EDIT: ['ROOM_DETAILS', 'ROOMS_STATUS'],
  ROOM_AGENDA: ['ROOM_DETAILS'],
  SERVICE_EVALUATION: ['EXEC_DASHBOARD'],
  PREDICTIVE_OCCUPANCY: ['EXEC_DASHBOARD'],
  AUDIT_LOG: ['GOVERNANCE', 'EXEC_DASHBOARD'],
  RADIANCE_DRILLDOWN: ['EXEC_DASHBOARD'],
  END: ['START']
};
