
export type BuscadorState =
  | 'START'
  | 'DASHBOARD'
  | 'ORACLE_PORTAL'
  | 'ORACLE_SHUFFLE'
  | 'ORACLE_REVEAL'
  | 'METAMORPHOSIS_CHECKIN'
  | 'METAMORPHOSIS_CAMERA'
  | 'METAMORPHOSIS_MESSAGE'
  | 'METAMORPHOSIS_RITUAL'
  | 'METAMORPHOSIS_FEEDBACK'
  | 'TRIBE_DASH'
  | 'TRIBE_INVITE'
  | 'TRIBE_INTERACTION'
  | 'BOOKING_SEARCH'
  | 'BOOKING_SELECT'
  | 'BOOKING_CONFIRM'
  | 'CHECKOUT'
  | 'PAYMENT_SUCCESS'
  | 'HISTORY'
  | 'PAYMENT_HISTORY'
  | 'CHAT_LIST'
  | 'CHAT_ROOM'
  | 'CHAT_SETTINGS'
  | 'CHAT_NEW'
  | 'GARDEN_VIEW'
  | 'EVOLUTION'
  | 'EVOLUTION_ANALYTICS'
    | 'EVOLUTION_ACHIEVEMENTS'
    | 'EVOLUTION_HISTORY'
    | 'EVOLUTION_TIMELAPSE'
    | 'TIME_LAPSE_EXPERIENCE'
    | 'TRIBE_VIEW'
    | 'TRIBE_DETAILS'
  | 'SETTINGS'
  | 'MARKETPLACE'
  | 'KARMA_WALLET'
  | 'ORACLE_HISTORY'
  | 'END';

export const transitions: Record<BuscadorState, BuscadorState[]> = {
  START: ['DASHBOARD', 'TRIBE_DASH', 'SETTINGS', 'MARKETPLACE', 'GARDEN_VIEW', 'ORACLE_PORTAL', 'METAMORPHOSIS_CHECKIN', 'BOOKING_SEARCH', 'BOOKING_SELECT', 'EVOLUTION'],
  DASHBOARD: ['ORACLE_PORTAL', 'METAMORPHOSIS_CHECKIN', 'TRIBE_DASH', 'BOOKING_SEARCH', 'CHAT_LIST', 'PAYMENT_HISTORY', 'GARDEN_VIEW', 'SETTINGS', 'MARKETPLACE', 'METAMORPHOSIS_RITUAL', 'HISTORY', 'EVOLUTION_TIMELAPSE'],
  ORACLE_PORTAL: ['ORACLE_SHUFFLE', 'DASHBOARD', 'ORACLE_HISTORY'],
  ORACLE_SHUFFLE: ['ORACLE_REVEAL'],
  ORACLE_REVEAL: ['DASHBOARD', 'ORACLE_PORTAL', 'ORACLE_HISTORY'],
  ORACLE_HISTORY: ['ORACLE_PORTAL', 'DASHBOARD'],
  METAMORPHOSIS_CHECKIN: ['METAMORPHOSIS_CAMERA', 'DASHBOARD', 'HISTORY'],
  METAMORPHOSIS_CAMERA: ['METAMORPHOSIS_MESSAGE', 'METAMORPHOSIS_CHECKIN'],
  METAMORPHOSIS_MESSAGE: ['METAMORPHOSIS_RITUAL'],
  METAMORPHOSIS_RITUAL: ['METAMORPHOSIS_FEEDBACK', 'DASHBOARD'],
  METAMORPHOSIS_FEEDBACK: ['DASHBOARD', 'HISTORY', 'EVOLUTION', 'METAMORPHOSIS_CHECKIN'],
  TRIBE_DASH: ['TRIBE_INVITE', 'TRIBE_INTERACTION', 'DASHBOARD', 'CHAT_LIST'],
  TRIBE_INVITE: ['TRIBE_DASH'],
  TRIBE_INTERACTION: ['TRIBE_DASH'],
  BOOKING_SEARCH: ['BOOKING_SELECT', 'DASHBOARD'],
  BOOKING_SELECT: ['BOOKING_CONFIRM', 'BOOKING_SEARCH'],
  BOOKING_CONFIRM: ['CHECKOUT', 'BOOKING_SELECT'],
  CHECKOUT: ['PAYMENT_SUCCESS', 'BOOKING_CONFIRM'],
  PAYMENT_SUCCESS: ['DASHBOARD', 'PAYMENT_HISTORY'],
  HISTORY: ['DASHBOARD', 'EVOLUTION', 'EVOLUTION_ANALYTICS', 'EVOLUTION_ACHIEVEMENTS', 'EVOLUTION_HISTORY', 'METAMORPHOSIS_CHECKIN', 'ORACLE_PORTAL'],
  PAYMENT_HISTORY: ['DASHBOARD'],
  CHAT_LIST: ['CHAT_ROOM', 'CHAT_NEW', 'DASHBOARD'],
  CHAT_ROOM: ['CHAT_SETTINGS', 'CHAT_LIST', 'DASHBOARD'],
  CHAT_SETTINGS: ['CHAT_ROOM'],
  CHAT_NEW: ['CHAT_ROOM', 'CHAT_LIST'],
  GARDEN_VIEW: ['DASHBOARD', 'HISTORY', 'EVOLUTION'],
  EVOLUTION: ['GARDEN_VIEW', 'EVOLUTION_ANALYTICS', 'EVOLUTION_ACHIEVEMENTS', 'EVOLUTION_HISTORY', 'HISTORY', 'TIME_LAPSE_EXPERIENCE', 'EVOLUTION_TIMELAPSE', 'DASHBOARD'],
  EVOLUTION_ANALYTICS: ['EVOLUTION', 'EVOLUTION_ACHIEVEMENTS', 'EVOLUTION_HISTORY', 'DASHBOARD'],
  EVOLUTION_ACHIEVEMENTS: ['EVOLUTION', 'EVOLUTION_ANALYTICS', 'EVOLUTION_HISTORY', 'DASHBOARD'],
  EVOLUTION_HISTORY: ['EVOLUTION', 'EVOLUTION_ANALYTICS', 'EVOLUTION_ACHIEVEMENTS', 'DASHBOARD'],
  TIME_LAPSE_EXPERIENCE: ['EVOLUTION', 'DASHBOARD'],
  EVOLUTION_TIMELAPSE: ['EVOLUTION', 'DASHBOARD'],
  TRIBE_VIEW: ['TRIBE_DASH'],
  TRIBE_DETAILS: ['TRIBE_VIEW'],
  SETTINGS: ['DASHBOARD', 'KARMA_WALLET'],
  MARKETPLACE: ['DASHBOARD', 'BOOKING_SEARCH'],
  KARMA_WALLET: ['DASHBOARD', 'MARKETPLACE', 'HISTORY', 'METAMORPHOSIS_CHECKIN', 'TRIBE_INVITE'],
  END: ['START']
};
