
export type BuscadorState =
  | 'START'
  | 'DASHBOARD'
  | 'ORACLE_PORTAL'
  | 'ORACLE_SHUFFLE'
  | 'ORACLE_REVEAL'
  | 'METAMORPHOSIS_CHECKIN'
  | 'METAMORPHOSIS_CAMERA'
  | 'METAMORPHOSIS_MESSAGE'
  | 'METAMORPHOSIS_RITUAL'
  | 'METAMORPHOSIS_FEEDBACK'
  | 'TRIBE_DASH'
  | 'TRIBE_INVITE'
  | 'TRIBE_INTERACTION'
  | 'HEALING_CIRCLE'
  | 'VIDEO_SESSION'
  | 'BOOKING_SEARCH'
  | 'BOOKING_SELECT'
  | 'BOOKING_CONFIRM'
  | 'CHECKOUT'
  | 'PAYMENT_SUCCESS'
  | 'HISTORY'
  | 'PAYMENT_HISTORY'
  | 'CHAT_LIST'
  | 'CHAT_ROOM'
  | 'CHAT_SETTINGS'
  | 'CHAT_NEW'
  | 'GARDEN_VIEW'
  | 'EVOLUTION'
  | 'EVOLUTION_ANALYTICS'
    | 'EVOLUTION_ACHIEVEMENTS'
    | 'EVOLUTION_HISTORY'
    | 'EVOLUTION_TIMELAPSE'
    | 'TIME_LAPSE_EXPERIENCE'
    | 'CLIENT_QUESTS'
  | 'SETTINGS'
  | 'MARKETPLACE'
  | 'KARMA_WALLET'
  | 'ORACLE_HISTORY'
  | 'EVO_GRIMOIRE'
  | 'CLIENT_JOURNAL'
  | 'SOUL_PACT'
  | 'OFFLINE_RETREAT'
  | 'END';

export const transitions: Record<BuscadorState, BuscadorState[]> = {
  START: ['DASHBOARD', 'ORACLE_PORTAL', 'TRIBE_DASH', 'SETTINGS', 'MARKETPLACE', 'GARDEN_VIEW', 'METAMORPHOSIS_CHECKIN', 'BOOKING_SEARCH', 'BOOKING_SELECT', 'EVOLUTION', 'PAYMENT_HISTORY', 'CLIENT_JOURNAL', 'EVOLUTION_TIMELAPSE', 'OFFLINE_RETREAT'],
  DASHBOARD: ['ORACLE_PORTAL', 'METAMORPHOSIS_CHECKIN', 'TRIBE_DASH', 'BOOKING_SEARCH', 'BOOKING_SELECT', 'CHAT_LIST', 'PAYMENT_HISTORY', 'GARDEN_VIEW', 'SETTINGS', 'MARKETPLACE', 'METAMORPHOSIS_RITUAL', 'HISTORY', 'EVOLUTION_TIMELAPSE', 'CLIENT_JOURNAL', 'EVOLUTION', 'KARMA_WALLET', 'OFFLINE_RETREAT', 'CLIENT_QUESTS'],
  ORACLE_PORTAL: ['ORACLE_SHUFFLE', 'DASHBOARD', 'ORACLE_HISTORY'],
  ORACLE_SHUFFLE: ['ORACLE_REVEAL'],
  ORACLE_REVEAL: ['DASHBOARD', 'ORACLE_PORTAL', 'ORACLE_HISTORY'],
  ORACLE_HISTORY: ['ORACLE_PORTAL', 'DASHBOARD'],
  METAMORPHOSIS_CHECKIN: ['METAMORPHOSIS_CAMERA', 'DASHBOARD', 'HISTORY', 'EVO_GRIMOIRE'],
  METAMORPHOSIS_CAMERA: ['METAMORPHOSIS_MESSAGE', 'METAMORPHOSIS_CHECKIN'],
  METAMORPHOSIS_MESSAGE: ['METAMORPHOSIS_FEEDBACK', 'METAMORPHOSIS_CHECKIN'],
  METAMORPHOSIS_RITUAL: ['DASHBOARD'],
  METAMORPHOSIS_FEEDBACK: ['DASHBOARD', 'HISTORY', 'EVOLUTION', 'METAMORPHOSIS_CHECKIN'],
  TRIBE_DASH: ['TRIBE_INVITE', 'TRIBE_INTERACTION', 'HEALING_CIRCLE', 'SOUL_PACT', 'DASHBOARD', 'OFFLINE_RETREAT'],
  TRIBE_INVITE: ['TRIBE_DASH', 'DASHBOARD'],
  TRIBE_INTERACTION: ['TRIBE_DASH', 'CHAT_ROOM', 'DASHBOARD'],
  BOOKING_SEARCH: ['BOOKING_SELECT', 'DASHBOARD'],
  BOOKING_SELECT: ['BOOKING_CONFIRM', 'BOOKING_SEARCH', 'DASHBOARD'],
  BOOKING_CONFIRM: ['CHECKOUT', 'BOOKING_SELECT', 'DASHBOARD', 'VIDEO_SESSION'],
  CHECKOUT: ['PAYMENT_SUCCESS', 'BOOKING_SEARCH', 'DASHBOARD'],
  PAYMENT_SUCCESS: ['DASHBOARD', 'HISTORY', 'PAYMENT_HISTORY', 'VIDEO_SESSION'],
  HISTORY: ['DASHBOARD', 'EVOLUTION', 'EVOLUTION_ANALYTICS', 'EVOLUTION_ACHIEVEMENTS', 'EVOLUTION_HISTORY', 'METAMORPHOSIS_CHECKIN', 'ORACLE_PORTAL', 'GARDEN_VIEW', 'TIME_LAPSE_EXPERIENCE', 'EVOLUTION_TIMELAPSE', 'CLIENT_JOURNAL'],
  PAYMENT_HISTORY: ['DASHBOARD', 'CHECKOUT'],
  CHAT_LIST: ['CHAT_ROOM', 'CHAT_NEW', 'CHAT_SETTINGS', 'DASHBOARD'],
  CHAT_ROOM: ['CHAT_LIST', 'DASHBOARD'],
  CHAT_SETTINGS: ['CHAT_LIST'],
  CHAT_NEW: ['CHAT_LIST', 'CHAT_ROOM'],
  GARDEN_VIEW: ['DASHBOARD', 'EVOLUTION', 'HISTORY', 'METAMORPHOSIS_CHECKIN', 'EVO_GRIMOIRE', 'CLIENT_JOURNAL', 'TRIBE_DASH', 'BOOKING_SEARCH', 'SETTINGS'],
  EVOLUTION: ['GARDEN_VIEW', 'EVOLUTION_ANALYTICS', 'EVOLUTION_ACHIEVEMENTS', 'EVOLUTION_HISTORY', 'HISTORY', 'TIME_LAPSE_EXPERIENCE', 'EVOLUTION_TIMELAPSE', 'DASHBOARD', 'CLIENT_JOURNAL', 'TRIBE_DASH', 'BOOKING_SEARCH', 'METAMORPHOSIS_CHECKIN'],
  EVOLUTION_ANALYTICS: ['EVOLUTION', 'HISTORY'],
  EVOLUTION_ACHIEVEMENTS: ['EVOLUTION', 'HISTORY'],
  EVOLUTION_HISTORY: ['EVOLUTION', 'HISTORY'],
  EVOLUTION_TIMELAPSE: ['EVOLUTION', 'TIME_LAPSE_EXPERIENCE', 'DASHBOARD', 'CLIENT_JOURNAL'],
  TIME_LAPSE_EXPERIENCE: ['EVOLUTION', 'EVOLUTION_TIMELAPSE'],
  CLIENT_QUESTS: ['DASHBOARD', 'KARMA_WALLET'],
  SETTINGS: ['DASHBOARD', 'START'],
  MARKETPLACE: ['DASHBOARD', 'CHECKOUT', 'KARMA_WALLET'],
  KARMA_WALLET: ['DASHBOARD', 'MARKETPLACE', 'HISTORY', 'METAMORPHOSIS_CHECKIN', 'TRIBE_INVITE'],
  EVO_GRIMOIRE: ['GARDEN_VIEW', 'DASHBOARD'],
  CLIENT_JOURNAL: ['DASHBOARD', 'HISTORY', 'GARDEN_VIEW', 'EVOLUTION', 'TRIBE_DASH', 'BOOKING_SEARCH', 'SETTINGS', 'METAMORPHOSIS_CHECKIN', 'EVOLUTION_TIMELAPSE'],
  HEALING_CIRCLE: ['CHECKOUT', 'TRIBE_DASH', 'DASHBOARD'],
  VIDEO_SESSION: ['DASHBOARD', 'HISTORY'],
  SOUL_PACT: ['TRIBE_DASH', 'DASHBOARD'],
  OFFLINE_RETREAT: ['TRIBE_DASH', 'DASHBOARD'],
  END: ['START'],
};
