
export type BuscadorState =
  | 'START'
  | 'DASHBOARD'
  | 'ORACLE_PORTAL'
  | 'ORACLE_SHUFFLE'
  | 'ORACLE_REVEAL'
  | 'METAMORPHOSIS_CHECKIN'
  | 'METAMORPHOSIS_CAMERA'
  | 'METAMORPHOSIS_MESSAGE'
  | 'METAMORPHOSIS_RITUAL'
  | 'METAMORPHOSIS_FEEDBACK'
  | 'TRIBE_DASH'
  | 'TRIBE_INVITE'
  | 'TRIBE_INTERACTION'
  | 'BOOKING_SEARCH'
  | 'BOOKING_SELECT'
  | 'BOOKING_CONFIRM'
  | 'CHECKOUT'
  | 'PAYMENT_SUCCESS'
  | 'HISTORY'
  | 'PAYMENT_HISTORY'
  | 'CHAT_LIST'
  | 'CHAT_ROOM'
  | 'CHAT_SETTINGS'
  | 'CHAT_NEW'
  | 'GARDEN_VIEW'
  | 'END';

export const transitions: Record<BuscadorState, BuscadorState[]> = {
  START: ['DASHBOARD'],
  DASHBOARD: ['ORACLE_PORTAL', 'METAMORPHOSIS_CHECKIN', 'TRIBE_DASH', 'BOOKING_SEARCH', 'CHAT_LIST', 'PAYMENT_HISTORY', 'GARDEN_VIEW'],
  ORACLE_PORTAL: ['ORACLE_SHUFFLE', 'DASHBOARD'],
  ORACLE_SHUFFLE: ['ORACLE_REVEAL'],
  ORACLE_REVEAL: ['DASHBOARD', 'ORACLE_PORTAL'],
  METAMORPHOSIS_CHECKIN: ['METAMORPHOSIS_CAMERA', 'DASHBOARD'],
  METAMORPHOSIS_CAMERA: ['METAMORPHOSIS_MESSAGE', 'METAMORPHOSIS_CHECKIN'],
  METAMORPHOSIS_MESSAGE: ['METAMORPHOSIS_RITUAL'],
  METAMORPHOSIS_RITUAL: ['METAMORPHOSIS_FEEDBACK'],
  METAMORPHOSIS_FEEDBACK: ['DASHBOARD'],
  TRIBE_DASH: ['TRIBE_INVITE', 'TRIBE_INTERACTION', 'DASHBOARD', 'CHAT_LIST'],
  TRIBE_INVITE: ['TRIBE_DASH'],
  TRIBE_INTERACTION: ['TRIBE_DASH'],
  BOOKING_SEARCH: ['BOOKING_SELECT', 'DASHBOARD'],
  BOOKING_SELECT: ['BOOKING_CONFIRM', 'BOOKING_SEARCH'],
  BOOKING_CONFIRM: ['CHECKOUT', 'BOOKING_SELECT'],
  CHECKOUT: ['PAYMENT_SUCCESS', 'BOOKING_CONFIRM'],
  PAYMENT_SUCCESS: ['DASHBOARD', 'PAYMENT_HISTORY'],
  HISTORY: ['DASHBOARD'],
  PAYMENT_HISTORY: ['DASHBOARD'],
  CHAT_LIST: ['CHAT_ROOM', 'CHAT_NEW', 'DASHBOARD'],
  CHAT_ROOM: ['CHAT_SETTINGS', 'CHAT_LIST', 'DASHBOARD'],
  CHAT_SETTINGS: ['CHAT_ROOM'],
  CHAT_NEW: ['CHAT_ROOM', 'CHAT_LIST'],
  GARDEN_VIEW: ['DASHBOARD'],
  END: ['START']
};
